# Generated by Django 5.1.6 on 2025-04-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="место и время для исполнения ",
                    ),
                ),
                ("scheduled_time", models.TimeField(verbose_name="время на покушать ")),
                ("activity", models.CharField(max_length=100, verbose_name="цель")),
                (
                    "is_enjoyable",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="талант от привычки",
                    ),
                ),
                ("periodicity", models.PositiveIntegerField(verbose_name="таймаут")),
                (
                    "bonus",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="приз"
                    ),
                ),
                (
                    "duration_to_complete",
                    models.PositiveIntegerField(
                        default=120, verbose_name="время работы"
                    ),
                ),
                (
                    "is_habit_public",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="общий признак",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
